services:
  rtsp_switcher:
    build:
      context: ./rtsp_switcher
      dockerfile: Dockerfile.local
    volumes:
      - ./rtsp_switcher/settings.yaml:/app/settings.yaml:ro
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, video]
    restart: unless-stopped
